# Generated by Django 3.0.2 on 2020-02-18 18:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('country', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('box_office', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(default='', max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('country', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('box_office', models.IntegerField()),
                ('feature_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('feature_description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MovieFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Feature')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.Movie'),
        ),
    ]
