# Generated by Django 3.0.2 on 2020-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
