# Generated by Django 3.0.2 on 2020-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('content', models.TextField(default=None, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
